greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_big_bigquery:
      type: bigquery
      method: service-account
      project: essential-graph-395008
      dataset: dbt_big #output
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/essential-graph-395008-dbt.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: essential-graph-395008
      dataset: prod
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/essential-graph-395008-dbt.json
      location: asia-southeast1

  target: dbt_big_bigquery